name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
      - name: Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
          git submodule update --init
          SYSDIR=`pwd`/sys
          cd src
          make SHELL=bash DEBUG=0 SYSDIR=$SYSDIR v
          cd ..
          rm -rf sys
  macos:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Macos
        run: |
          git submodule update --init
          SYSDIR=`pwd`/sys
          cd src
          make SHELL=bash DEBUG=0 SYSDIR=$SYSDIR v
          cd ..
          rm -rf sys
